### ISSUE TITLE
Картинки

### ISSUE THREAD

**Issue by zluca** [everypony/twicher#3]
### Проблема

Некоторые картинки умерли. Другие залиты на левые ненадёжные хостинги.
<img src="https://cdn.everypony.ru/storage/02/43/83/2016/10/03/165703d551.png" />
### Решение

Перезалить всё на табунский кдн.

**Comment by Orhideous** [comment]
Дело в том, что они не все есть. И не все их можно вытащить.

**Comment by zluca** [comment]
Тогда лучше удалить вообще нерабочую картинку. Или даже саму цитату если там смысл от картинки зависит.

**Comment by Orhideous** [comment]
Да, они потом поудаляются,
